title: Lillian Chen - Front End Developer
author: Lillian Chen
description: >
  Lily is currently a developer at IBM Watson Health based in Cambridge, Massachusetts. 
  She recently graduated from Cornell studying computer science.
keywords: developer,cornell,ibm,web,front-end,backend,design,jquery,node,rails,ruby,django,HTML,CSS,javascript
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://lillian-chen.com/"
permalink: none

# Contact
email: 			    iam@lillian-chen.com
twitter_url:    https://twitter.com/lllychen
twitter_handle: "@lllychen"
github_url:     https://github.com/lllychen
linkedin_url:   https://www.linkedin.com/in/lllychen

# Build settings
sass:
  style: compressed
markdown: kramdown
highlighter: rouge
exclude: ['node_modules', 'gulpfile.js', 'package.json', 'assets/psd']
include: ['_scss', '*.scss', '.htaccess']
