title: Lily Chen
author: Lily Chen
description: >
  Lily is currently a Product Designer at AngelList. Previously, IBM and Cornell.
keywords: product,designer,angellist,ibm,cornell
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://lilywork.netlify.com/"
permalink: none

# Contact
email:          lilyc5459@gmail.com
twitter_url:    https://twitter.com/lllychen
twitter_handle: "@lllychen"
github_url:     https://github.com/lllychen
linkedin_url:   https://www.linkedin.com/in/lllychen

# Build settings
sass:
  sass_dir: ./_scss
  style: compressed
exclude: ['node_modules', 'gulpfile.js', 'package.json']

defaults:
  -
    scope:
      path: "blog/_posts/*"
    values:
      layout: "post"
      category: "blog"
  -
    scope:
      path: "work/_posts/*"
    values:
      layout: "post"
      category: "work"